name = "MosaicPlots"
uuid = "915c28b8-c72c-4283-942e-caa56abaefd2"
authors = ["Sahraoui Tarik Ziad <sahraouitarikziad@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"
Plots = "1"